/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "CometChat Docs",
  "url": "https://www.cometchat.com",
  "baseUrl": "/docs/",
  "favicon": "/homepage/logo.png",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "onBrokenLinks": "warn",
  "plugins": [
    null,
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/react-chat-ui-kit.js",
        "id": "react-chat-ui-kit",
        "path": "docs/ui-kits/react",
        "routeBasePath": "/ui-kit/react",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v6",
            "path": "v6"
          },
          "5.0": {
            "label": "v5",
            "path": "v5"
          },
          "4.0": {
            "label": "v4",
            "path": "v4"
          },
          "3.0": {
            "label": "v3",
            "path": "v3"
          },
          "2.0": {
            "label": "v2",
            "path": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/vue-chat-ui-kit.js",
        "id": "vue-chat-ui-kit",
        "path": "docs/ui-kits/vue",
        "routeBasePath": "/ui-kit/vue",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "3.0": {
            "label": "v3"
          },
          "2.0": {
            "label": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/angular-chat-ui-kit.js",
        "id": "angular-chat-ui-kit",
        "path": "docs/ui-kits/angular",
        "routeBasePath": "/ui-kit/angular",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "3.0": {
            "label": "v3"
          },
          "2.0": {
            "label": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/react-native-chat-ui-kit.js",
        "id": "react-native-chat-ui-kit",
        "path": "docs/ui-kits/react-native",
        "routeBasePath": "/ui-kit/react-native",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "3.0": {
            "label": "v3"
          },
          "2.0": {
            "label": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/android-chat-ui-kit.js",
        "id": "android-chat-ui-kit",
        "path": "docs/ui-kits/android",
        "routeBasePath": "/ui-kit/android",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v5",
            "path": "v5"
          },
          "4.0": {
            "label": "v4",
            "path": "v4"
          },
          "3.0": {
            "label": "v3",
            "path": "v3"
          },
          "2.0": {
            "label": "v2",
            "path": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/ios-chat-ui-kit.js",
        "id": "ios-chat-ui-kit",
        "path": "docs/ui-kits/ios",
        "routeBasePath": "/ui-kit/ios",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v5",
            "path": "v5"
          },
          "4.0": {
            "label": "v4",
            "path": "v4"
          },
          "3.0": {
            "label": "v3",
            "path": "v3"
          },
          "2.0": {
            "label": "v2",
            "path": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/flutter-chat-ui-kit.js",
        "id": "flutter-chat-ui-kit",
        "path": "docs/ui-kits/flutter",
        "routeBasePath": "/ui-kit/flutter",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "5.0": {
            "label": "v5",
            "banner": "none"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "web-shared",
        "path": "docs/ui-kits/web-shared",
        "routeBasePath": "/web-shared",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "elements",
        "path": "docs/ui-kits/elements",
        "routeBasePath": "/web-elements",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/javascript-chat-sdk.js",
        "id": "javascript-chat-sdk",
        "path": "docs/sdk/javascript",
        "routeBasePath": "/sdk/javascript",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "3.0": {
            "label": "v3"
          },
          "2.0": {
            "label": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/android-chat-sdk.js",
        "id": "android-chat-sdk",
        "path": "docs/sdk/android",
        "routeBasePath": "/sdk/android",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "3.0": {
            "label": "v3"
          },
          "2.0": {
            "label": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/flutter-chat-sdk.js",
        "id": "flutter-chat-sdk",
        "path": "docs/sdk/flutter",
        "routeBasePath": "/sdk/flutter",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "3.0": {
            "label": "v3"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/ios-chat-sdk.js",
        "id": "ios-chat-sdk",
        "path": "docs/sdk/ios",
        "routeBasePath": "/sdk/ios",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "3.0": {
            "label": "v3"
          },
          "2.0": {
            "label": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/react-native-chat-sdk.js",
        "id": "react-native-chat-sdk",
        "path": "docs/sdk/react-native",
        "routeBasePath": "/sdk/react-native",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "3.0": {
            "label": "v3"
          },
          "2.0": {
            "label": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/ionic-chat-sdk.js",
        "id": "ionic-chat-sdk",
        "path": "docs/sdk/ionic",
        "routeBasePath": "/sdk/ionic",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          },
          "3.0": {
            "label": "v3"
          },
          "2.0": {
            "label": "v2"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "react-call-sdk",
        "path": "docs/sdk-call/react",
        "routeBasePath": "/calling/sdk/react",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "react-native-call-sdk",
        "path": "docs/sdk-call/react-native",
        "routeBasePath": "/calling/sdk/react-native",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "ionic-call-sdk",
        "path": "docs/sdk-call/ionic",
        "routeBasePath": "/calling/sdk/ionic",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "flutter-call-sdk",
        "path": "docs/sdk-call/flutter",
        "routeBasePath": "/calling/sdk/flutter",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "android-call-sdk",
        "path": "docs/sdk-call/android",
        "routeBasePath": "/calling/sdk/android",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "ios-call-sdk",
        "path": "docs/sdk-call/ios",
        "routeBasePath": "/calling/sdk/ios",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "chat-widgets",
        "path": "docs/chat-widgets",
        "routeBasePath": "/widget",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "articles",
        "path": "docs/articles",
        "routeBasePath": "/articles",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "extensions",
        "path": "docs/extend/extensions",
        "routeBasePath": "/extensions",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "notifications",
        "path": "docs/notifications",
        "routeBasePath": "/notifications",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "fundamentals",
        "path": "docs/fundamentals",
        "routeBasePath": "/fundamentals",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "ai-chatbots",
        "path": "docs/extend/ai-chatbots",
        "routeBasePath": "/ai-chatbots",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "insights",
        "path": "docs/extend/insights",
        "routeBasePath": "/insights",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/docs/sidebars/moderation.js",
        "id": "moderation",
        "path": "docs/extend/moderation",
        "routeBasePath": "/moderation",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v4"
          }
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "breadcrumbs": true,
        "showLastUpdateTime": true,
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ],
        "sidebarPath": "/home/jawangana/docs/sidebar_auto.js",
        "id": "android-kotlin-chat-ui-kit",
        "path": "docs/ui-kits/android-kotlin",
        "routeBasePath": "/ui-kit/kotlin",
        "lastVersion": "current",
        "versions": {
          "current": {
            "label": "v3"
          },
          "2.0": {
            "label": "v2"
          }
        }
      }
    ],
    null,
    [
      "docusaurus2-dotenv",
      {
        "systemvars": false
      }
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": [
          {
            "from": "/ui-kit/react",
            "to": "/ui-kit/react/v6/overview"
          },
          {
            "from": "/ui-kit/react/v6",
            "to": "/ui-kit/react/v6/overview"
          },
          {
            "from": "/ui-kit/react/v5",
            "to": "/ui-kit/react/v5/overview"
          },
          {
            "from": "/ui-kit/react/5.0",
            "to": "/ui-kit/react/v5/overview"
          },
          {
            "from": "/ui-kit/react/4.0",
            "to": "/ui-kit/react/v4/overview"
          },
          {
            "from": "/ui-kit/react/3.0",
            "to": "/ui-kit/react/v3/overview"
          },
          {
            "from": "/ui-kit/react/2.0",
            "to": "/ui-kit/react/v2/overview"
          },
          {
            "from": "/ui-kit/react/overview",
            "to": "/ui-kit/react/v5/overview"
          },
          {
            "from": "/ui-kit/react/5.0/overview",
            "to": "/ui-kit/react/v5/overview"
          },
          {
            "from": "/ui-kit/react/integration",
            "to": "/ui-kit/react/v5/integration"
          },
          {
            "from": "/ui-kit/react/5.0/integration",
            "to": "/ui-kit/react/v5/integration"
          },
          {
            "from": "/ui-kit/react/integration/next-js",
            "to": "/ui-kit/react/v5/integration/next-js"
          },
          {
            "from": "/ui-kit/react/5.0/integration/next-js",
            "to": "/ui-kit/react/v5/integration/next-js"
          },
          {
            "from": "/ui-kit/react/core-features",
            "to": "/ui-kit/react/v5/core-features"
          },
          {
            "from": "/ui-kit/react/5.0/core-features",
            "to": "/ui-kit/react/v5/core-features"
          },
          {
            "from": "/ui-kit/react/extensions",
            "to": "/ui-kit/react/v5/extensions"
          },
          {
            "from": "/ui-kit/react/5.0/extensions",
            "to": "/ui-kit/react/v5/extensions"
          },
          {
            "from": "/ui-kit/react/ai-features",
            "to": "/ui-kit/react/v5/ai-features"
          },
          {
            "from": "/ui-kit/react/5.0/ai-features",
            "to": "/ui-kit/react/v5/ai-features"
          },
          {
            "from": "/ui-kit/react/call-features",
            "to": "/ui-kit/react/v5/call-features"
          },
          {
            "from": "/ui-kit/react/5.0/call-features",
            "to": "/ui-kit/react/v5/call-features"
          },
          {
            "from": "/ui-kit/react/theme",
            "to": "/ui-kit/react/v5/theme"
          },
          {
            "from": "/ui-kit/react/5.0/theme",
            "to": "/ui-kit/react/v5/theme"
          },
          {
            "from": "/ui-kit/react/theme/color-resources",
            "to": "/ui-kit/react/v5/theme/color-resources"
          },
          {
            "from": "/ui-kit/react/5.0/theme/color-resources",
            "to": "/ui-kit/react/v5/theme/color-resources"
          },
          {
            "from": "/ui-kit/react/theme/message-bubble-styling",
            "to": "/ui-kit/react/v5/theme/message-bubble-styling"
          },
          {
            "from": "/ui-kit/react/5.0/theme/message-bubble-styling",
            "to": "/ui-kit/react/v5/theme/message-bubble-styling"
          },
          {
            "from": "/ui-kit/react/localize",
            "to": "/ui-kit/react/v5/localize"
          },
          {
            "from": "/ui-kit/react/5.0/localize",
            "to": "/ui-kit/react/v5/localize"
          },
          {
            "from": "/ui-kit/react/sound-manager",
            "to": "/ui-kit/react/v5/sound-manager"
          },
          {
            "from": "/ui-kit/react/5.0/sound-manager",
            "to": "/ui-kit/react/v5/sound-manager"
          },
          {
            "from": "/ui-kit/react/components-overview",
            "to": "/ui-kit/react/v5/components-overview"
          },
          {
            "from": "/ui-kit/react/5.0/components-overview",
            "to": "/ui-kit/react/v5/components-overview"
          },
          {
            "from": "/ui-kit/react/conversations",
            "to": "/ui-kit/react/v5/conversations"
          },
          {
            "from": "/ui-kit/react/5.0/conversations",
            "to": "/ui-kit/react/v5/conversations"
          },
          {
            "from": "/ui-kit/react/users",
            "to": "/ui-kit/react/v5/users"
          },
          {
            "from": "/ui-kit/react/5.0/users",
            "to": "/ui-kit/react/v5/users"
          },
          {
            "from": "/ui-kit/react/groups",
            "to": "/ui-kit/react/v5/groups"
          },
          {
            "from": "/ui-kit/react/5.0/groups",
            "to": "/ui-kit/react/v5/groups"
          },
          {
            "from": "/ui-kit/react/group-members",
            "to": "/ui-kit/react/v5/group-members"
          },
          {
            "from": "/ui-kit/react/5.0/group-members",
            "to": "/ui-kit/react/v5/group-members"
          },
          {
            "from": "/ui-kit/react/message-header",
            "to": "/ui-kit/react/v5/message-header"
          },
          {
            "from": "/ui-kit/react/5.0/message-header",
            "to": "/ui-kit/react/v5/message-header"
          },
          {
            "from": "/ui-kit/react/message-list",
            "to": "/ui-kit/react/v5/message-list"
          },
          {
            "from": "/ui-kit/react/5.0/message-list",
            "to": "/ui-kit/react/v5/message-list"
          },
          {
            "from": "/ui-kit/react/message-composer",
            "to": "/ui-kit/react/v5/message-composer"
          },
          {
            "from": "/ui-kit/react/5.0/message-composer",
            "to": "/ui-kit/react/v5/message-composer"
          },
          {
            "from": "/ui-kit/react/message-template",
            "to": "/ui-kit/react/v5/message-template"
          },
          {
            "from": "/ui-kit/react/5.0/message-template",
            "to": "/ui-kit/react/v5/message-template"
          },
          {
            "from": "/ui-kit/react/threaded-message-preview",
            "to": "/ui-kit/react/v5/threaded-message-preview"
          },
          {
            "from": "/ui-kit/react/5.0/threaded-message-preview",
            "to": "/ui-kit/react/v5/threaded-message-preview"
          },
          {
            "from": "/ui-kit/react/incoming-call",
            "to": "/ui-kit/react/v5/incoming-call"
          },
          {
            "from": "/ui-kit/react/5.0/incoming-call",
            "to": "/ui-kit/react/v5/incoming-call"
          },
          {
            "from": "/ui-kit/react/outgoing-call",
            "to": "/ui-kit/react/v5/outgoing-call"
          },
          {
            "from": "/ui-kit/react/5.0/outgoing-call",
            "to": "/ui-kit/react/v5/outgoing-call"
          },
          {
            "from": "/ui-kit/react/call-buttons",
            "to": "/ui-kit/react/v5/call-buttons"
          },
          {
            "from": "/ui-kit/react/5.0/call-buttons",
            "to": "/ui-kit/react/v5/call-buttons"
          },
          {
            "from": "/ui-kit/react/call-logs",
            "to": "/ui-kit/react/v5/call-logs"
          },
          {
            "from": "/ui-kit/react/5.0/call-logs",
            "to": "/ui-kit/react/v5/call-logs"
          },
          {
            "from": "/ui-kit/react/events",
            "to": "/ui-kit/react/v5/events"
          },
          {
            "from": "/ui-kit/react/5.0/events",
            "to": "/ui-kit/react/v5/events"
          },
          {
            "from": "/ui-kit/react/methods",
            "to": "/ui-kit/react/v5/methods"
          },
          {
            "from": "/ui-kit/react/5.0/methods",
            "to": "/ui-kit/react/v5/methods"
          },
          {
            "from": "/ui-kit/react/custom-text-formatter-guide",
            "to": "/ui-kit/react/v5/custom-text-formatter-guide"
          },
          {
            "from": "/ui-kit/react/5.0/custom-text-formatter-guide",
            "to": "/ui-kit/react/v5/custom-text-formatter-guide"
          },
          {
            "from": "/ui-kit/react/mentions-formatter-guide",
            "to": "/ui-kit/react/v5/mentions-formatter-guide"
          },
          {
            "from": "/ui-kit/react/5.0/mentions-formatter-guide",
            "to": "/ui-kit/react/v5/mentions-formatter-guide"
          },
          {
            "from": "/ui-kit/react/url-formatter-guide",
            "to": "/ui-kit/react/v5/url-formatter-guide"
          },
          {
            "from": "/ui-kit/react/5.0/url-formatter-guide",
            "to": "/ui-kit/react/v5/url-formatter-guide"
          },
          {
            "from": "/ui-kit/react/shortcut-formatter-guide",
            "to": "/ui-kit/react/v5/shortcut-formatter-guide"
          },
          {
            "from": "/ui-kit/react/5.0/shortcut-formatter-guide",
            "to": "/ui-kit/react/v5/shortcut-formatter-guide"
          },
          {
            "from": "/ui-kit/react/upgrading-from-v4",
            "to": "/ui-kit/react/v5/upgrading-from-v4"
          },
          {
            "from": "/ui-kit/react/5.0/upgrading-from-v4",
            "to": "/ui-kit/react/v5/upgrading-from-v4"
          },
          {
            "from": "/ui-kit/react/property-changes",
            "to": "/ui-kit/react/v5/property-changes"
          },
          {
            "from": "/ui-kit/react/5.0/property-changes",
            "to": "/ui-kit/react/v5/property-changes"
          },
          {
            "from": "/ui-kit/react/4.0/overview",
            "to": "/ui-kit/react/v4/overview"
          },
          {
            "from": "/ui-kit/react/4.0/getting-started",
            "to": "/ui-kit/react/v4/getting-started"
          },
          {
            "from": "/ui-kit/react/4.0/core-features",
            "to": "/ui-kit/react/v4/core-features"
          },
          {
            "from": "/ui-kit/react/4.0/extensions",
            "to": "/ui-kit/react/v4/extensions"
          },
          {
            "from": "/ui-kit/react/4.0/call-features",
            "to": "/ui-kit/react/v4/call-features"
          },
          {
            "from": "/ui-kit/react/4.0/ai-features",
            "to": "/ui-kit/react/v4/ai-features"
          },
          {
            "from": "/ui-kit/react/4.0/theme",
            "to": "/ui-kit/react/v4/theme"
          },
          {
            "from": "/ui-kit/react/4.0/localize",
            "to": "/ui-kit/react/v4/localize"
          },
          {
            "from": "/ui-kit/react/4.0/sound-manager",
            "to": "/ui-kit/react/v4/sound-manager"
          },
          {
            "from": "/ui-kit/react/4.0/components-overview",
            "to": "/ui-kit/react/v4/components-overview"
          },
          {
            "from": "/ui-kit/react/4.0/conversations",
            "to": "/ui-kit/react/v4/conversations"
          },
          {
            "from": "/ui-kit/react/4.0/conversations-with-messages",
            "to": "/ui-kit/react/v4/conversations-with-messages"
          },
          {
            "from": "/ui-kit/react/4.0/contacts",
            "to": "/ui-kit/react/v4/contacts"
          },
          {
            "from": "/ui-kit/react/4.0/users",
            "to": "/ui-kit/react/v4/users"
          },
          {
            "from": "/ui-kit/react/4.0/users-with-messages",
            "to": "/ui-kit/react/v4/users-with-messages"
          },
          {
            "from": "/ui-kit/react/4.0/users-details",
            "to": "/ui-kit/react/v4/users-details"
          },
          {
            "from": "/ui-kit/react/4.0/groups",
            "to": "/ui-kit/react/v4/groups"
          },
          {
            "from": "/ui-kit/react/4.0/groups-with-messages",
            "to": "/ui-kit/react/v4/groups-with-messages"
          },
          {
            "from": "/ui-kit/react/4.0/create-group",
            "to": "/ui-kit/react/v4/create-group"
          },
          {
            "from": "/ui-kit/react/4.0/join-protected-group",
            "to": "/ui-kit/react/v4/join-protected-group"
          },
          {
            "from": "/ui-kit/react/4.0/group-members",
            "to": "/ui-kit/react/v4/group-members"
          },
          {
            "from": "/ui-kit/react/4.0/group-add-members",
            "to": "/ui-kit/react/v4/group-add-members"
          },
          {
            "from": "/ui-kit/react/4.0/group-banned-members",
            "to": "/ui-kit/react/v4/group-banned-members"
          },
          {
            "from": "/ui-kit/react/4.0/group-transfer-ownership",
            "to": "/ui-kit/react/v4/group-transfer-ownership"
          },
          {
            "from": "/ui-kit/react/4.0/group-details",
            "to": "/ui-kit/react/v4/group-details"
          },
          {
            "from": "/ui-kit/react/4.0/messages",
            "to": "/ui-kit/react/v4/messages"
          },
          {
            "from": "/ui-kit/react/4.0/message-header",
            "to": "/ui-kit/react/v4/message-header"
          },
          {
            "from": "/ui-kit/react/4.0/message-list",
            "to": "/ui-kit/react/v4/message-list"
          },
          {
            "from": "/ui-kit/react/4.0/message-template",
            "to": "/ui-kit/react/v4/message-template"
          },
          {
            "from": "/ui-kit/react/4.0/message-composer",
            "to": "/ui-kit/react/v4/message-composer"
          },
          {
            "from": "/ui-kit/react/4.0/message-information",
            "to": "/ui-kit/react/v4/message-information"
          },
          {
            "from": "/ui-kit/react/4.0/threaded-messages",
            "to": "/ui-kit/react/v4/threaded-messages"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-form-message",
            "to": "/ui-kit/react/v4/interactive-form-message"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-form-bubble",
            "to": "/ui-kit/react/v4/interactive-form-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-card-message",
            "to": "/ui-kit/react/v4/interactive-card-message"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-card-bubble",
            "to": "/ui-kit/react/v4/interactive-card-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-element-type",
            "to": "/ui-kit/react/v4/interactive-element-type"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-action-entity",
            "to": "/ui-kit/react/v4/interactive-action-entity"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-custom-interactive-message",
            "to": "/ui-kit/react/v4/interactive-custom-interactive-message"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-button-element",
            "to": "/ui-kit/react/v4/interactive-button-element"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-text-input-element",
            "to": "/ui-kit/react/v4/interactive-text-input-element"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-label-element",
            "to": "/ui-kit/react/v4/interactive-label-element"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-single-select-element",
            "to": "/ui-kit/react/v4/interactive-single-select-element"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-radio-button-element",
            "to": "/ui-kit/react/v4/interactive-radio-button-element"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-checkbox-element",
            "to": "/ui-kit/react/v4/interactive-checkbox-element"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-dropdown-element",
            "to": "/ui-kit/react/v4/interactive-dropdown-element"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-scheduler-message",
            "to": "/ui-kit/react/v4/interactive-scheduler-message"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-scheduler-bubble",
            "to": "/ui-kit/react/v4/interactive-scheduler-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/interactive-date-time-picker-element",
            "to": "/ui-kit/react/v4/interactive-date-time-picker-element"
          },
          {
            "from": "/ui-kit/react/4.0/call-overview",
            "to": "/ui-kit/react/v4/call-overview"
          },
          {
            "from": "/ui-kit/react/4.0/incoming-call",
            "to": "/ui-kit/react/v4/incoming-call"
          },
          {
            "from": "/ui-kit/react/4.0/ongoing-call",
            "to": "/ui-kit/react/v4/ongoing-call"
          },
          {
            "from": "/ui-kit/react/4.0/outgoing-call",
            "to": "/ui-kit/react/v4/outgoing-call"
          },
          {
            "from": "/ui-kit/react/4.0/call-buttons",
            "to": "/ui-kit/react/v4/call-buttons"
          },
          {
            "from": "/ui-kit/react/4.0/call-logs",
            "to": "/ui-kit/react/v4/call-logs"
          },
          {
            "from": "/ui-kit/react/4.0/call-log-details",
            "to": "/ui-kit/react/v4/call-log-details"
          },
          {
            "from": "/ui-kit/react/4.0/call-log-history",
            "to": "/ui-kit/react/v4/call-log-history"
          },
          {
            "from": "/ui-kit/react/4.0/call-log-recording",
            "to": "/ui-kit/react/v4/call-log-recording"
          },
          {
            "from": "/ui-kit/react/4.0/call-log-participants",
            "to": "/ui-kit/react/v4/call-log-participants"
          },
          {
            "from": "/ui-kit/react/4.0/call-log-with-details",
            "to": "/ui-kit/react/v4/call-log-with-details"
          },
          {
            "from": "/ui-kit/react/4.0/reaction",
            "to": "/ui-kit/react/v4/reaction"
          },
          {
            "from": "/ui-kit/react/4.0/reaction-list",
            "to": "/ui-kit/react/v4/reaction-list"
          },
          {
            "from": "/ui-kit/react/4.0/reaction-info",
            "to": "/ui-kit/react/v4/reaction-info"
          },
          {
            "from": "/ui-kit/react/4.0/user-member-wrapper",
            "to": "/ui-kit/react/v4/user-member-wrapper"
          },
          {
            "from": "/ui-kit/react/4.0/avatar",
            "to": "/ui-kit/react/v4/avatar"
          },
          {
            "from": "/ui-kit/react/4.0/status-indicator",
            "to": "/ui-kit/react/v4/status-indicator"
          },
          {
            "from": "/ui-kit/react/4.0/badge",
            "to": "/ui-kit/react/v4/badge"
          },
          {
            "from": "/ui-kit/react/4.0/receipt",
            "to": "/ui-kit/react/v4/receipt"
          },
          {
            "from": "/ui-kit/react/4.0/date",
            "to": "/ui-kit/react/v4/date"
          },
          {
            "from": "/ui-kit/react/4.0/text-bubble",
            "to": "/ui-kit/react/v4/text-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/image-bubble",
            "to": "/ui-kit/react/v4/image-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/file-bubble",
            "to": "/ui-kit/react/v4/file-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/audio-bubble",
            "to": "/ui-kit/react/v4/audio-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/video-bubble",
            "to": "/ui-kit/react/v4/video-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/message-bubble",
            "to": "/ui-kit/react/v4/message-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/document-bubble",
            "to": "/ui-kit/react/v4/document-bubble"
          },
          {
            "from": "/ui-kit/react/4.0/message-input",
            "to": "/ui-kit/react/v4/message-input"
          },
          {
            "from": "/ui-kit/react/4.0/action-sheet",
            "to": "/ui-kit/react/v4/action-sheet"
          },
          {
            "from": "/ui-kit/react/4.0/media-recorder",
            "to": "/ui-kit/react/v4/media-recorder"
          },
          {
            "from": "/ui-kit/react/4.0/list-item",
            "to": "/ui-kit/react/v4/list-item"
          },
          {
            "from": "/ui-kit/react/4.0/confirm-dialog",
            "to": "/ui-kit/react/v4/confirm-dialog"
          },
          {
            "from": "/ui-kit/react/4.0/backdrop",
            "to": "/ui-kit/react/v4/backdrop"
          },
          {
            "from": "/ui-kit/react/4.0/emoji-keyboard",
            "to": "/ui-kit/react/v4/emoji-keyboard"
          },
          {
            "from": "/ui-kit/react/4.0/modal",
            "to": "/ui-kit/react/v4/modal"
          },
          {
            "from": "/ui-kit/react/4.0/pop-over",
            "to": "/ui-kit/react/v4/pop-over"
          },
          {
            "from": "/ui-kit/react/4.0/icon",
            "to": "/ui-kit/react/v4/icon"
          },
          {
            "from": "/ui-kit/react/4.0/loader",
            "to": "/ui-kit/react/v4/loader"
          },
          {
            "from": "/ui-kit/react/4.0/icon-button",
            "to": "/ui-kit/react/v4/icon-button"
          },
          {
            "from": "/ui-kit/react/4.0/button-group",
            "to": "/ui-kit/react/v4/button-group"
          },
          {
            "from": "/ui-kit/react/4.0/label",
            "to": "/ui-kit/react/v4/label"
          },
          {
            "from": "/ui-kit/react/4.0/input",
            "to": "/ui-kit/react/v4/input"
          },
          {
            "from": "/ui-kit/react/4.0/search-input",
            "to": "/ui-kit/react/v4/search-input"
          },
          {
            "from": "/ui-kit/react/4.0/checkbox",
            "to": "/ui-kit/react/v4/checkbox"
          },
          {
            "from": "/ui-kit/react/4.0/radio-button",
            "to": "/ui-kit/react/v4/radio-button"
          },
          {
            "from": "/ui-kit/react/4.0/dropdown",
            "to": "/ui-kit/react/v4/dropdown"
          },
          {
            "from": "/ui-kit/react/4.0/cometchat-quick-view",
            "to": "/ui-kit/react/v4/cometchat-quick-view"
          },
          {
            "from": "/ui-kit/react/4.0/singleselect",
            "to": "/ui-kit/react/v4/singleselect"
          },
          {
            "from": "/ui-kit/react/4.0/list",
            "to": "/ui-kit/react/v4/list"
          },
          {
            "from": "/ui-kit/react/4.0/events",
            "to": "/ui-kit/react/v4/events"
          },
          {
            "from": "/ui-kit/react/4.0/methods",
            "to": "/ui-kit/react/v4/methods"
          },
          {
            "from": "/ui-kit/react/4.0/multi-tab-chat-ui-guide",
            "to": "/ui-kit/react/v4/multi-tab-chat-ui-guide"
          },
          {
            "from": "/ui-kit/react/4.0/next-js-integration-guide",
            "to": "/ui-kit/react/v4/next-js-integration-guide"
          },
          {
            "from": "/ui-kit/react/4.0/custom-text-formatter-guide",
            "to": "/ui-kit/react/v4/custom-text-formatter-guide"
          },
          {
            "from": "/ui-kit/react/4.0/mentions-formatter-guide",
            "to": "/ui-kit/react/v4/mentions-formatter-guide"
          },
          {
            "from": "/ui-kit/react/4.0/url-formatter-guide",
            "to": "/ui-kit/react/v4/url-formatter-guide"
          },
          {
            "from": "/ui-kit/react/4.0/shortcut-formatter-guide",
            "to": "/ui-kit/react/v4/shortcut-formatter-guide"
          },
          {
            "from": "/ui-kit/react/3.0/key-concepts",
            "to": "/ui-kit/react/v3/key-concepts"
          },
          {
            "from": "/ui-kit/react/3.0/overview",
            "to": "/ui-kit/react/v3/overview"
          },
          {
            "from": "/ui-kit/react/3.0/ui-components",
            "to": "/ui-kit/react/v3/ui-components"
          },
          {
            "from": "/ui-kit/react/3.0/customize",
            "to": "/ui-kit/react/v3/customize"
          },
          {
            "from": "/ui-kit/react/3.0/nextjs",
            "to": "/ui-kit/react/v3/nextjs"
          },
          {
            "from": "/ui-kit/react/2.0/key-concepts",
            "to": "/ui-kit/react/v2/key-concepts"
          },
          {
            "from": "/ui-kit/react/2.0/message-structure-and-hierarchy",
            "to": "/ui-kit/react/v2/message-structure-and-hierarchy"
          },
          {
            "from": "/ui-kit/react/2.0/overview",
            "to": "/ui-kit/react/v2/overview"
          },
          {
            "from": "/ui-kit/react/2.0/ui-components",
            "to": "/ui-kit/react/v2/ui-components"
          },
          {
            "from": "/ui-kit/react/2.0/customize-ui-kit",
            "to": "/ui-kit/react/v2/customize-ui-kit"
          },
          {
            "from": "/ui-kit/react/2.0/integration-with-nextjs",
            "to": "/ui-kit/react/v2/integration-with-nextjs"
          },
          {
            "from": "/ui-kit/react/v6/integration",
            "to": "/ui-kit/react/v6/react-js-integration"
          },
          {
            "from": "/ui-kit/react/v6/integration/next-js",
            "to": "/ui-kit/react/v6/next-js-integration"
          },
          {
            "from": "/ui-kit/android",
            "to": "/ui-kit/android/v5/overview"
          },
          {
            "from": "/ui-kit/android/v5",
            "to": "/ui-kit/android/v5/overview"
          },
          {
            "from": "/ui-kit/android/v4",
            "to": "/ui-kit/android/v4/overview"
          },
          {
            "from": "/ui-kit/android/5.0",
            "to": "/ui-kit/android/v5/overview"
          },
          {
            "from": "/ui-kit/android/4.0",
            "to": "/ui-kit/android/v4/overview"
          },
          {
            "from": "/ui-kit/android/3.0",
            "to": "/ui-kit/android/v3/overview"
          },
          {
            "from": "/ui-kit/android/2.0",
            "to": "/ui-kit/android/v2/overview"
          },
          {
            "from": "/ui-kit/android/5.0/overview",
            "to": "/ui-kit/android/v5/overview"
          },
          {
            "from": "/ui-kit/android/5.0/getting-started",
            "to": "/ui-kit/android/v5/getting-started"
          },
          {
            "from": "/ui-kit/android/5.0/core-features",
            "to": "/ui-kit/android/v5/core-features"
          },
          {
            "from": "/ui-kit/android/5.0/extensions",
            "to": "/ui-kit/android/v5/extensions"
          },
          {
            "from": "/ui-kit/android/5.0/ai-features",
            "to": "/ui-kit/android/v5/ai-features"
          },
          {
            "from": "/ui-kit/android/5.0/call-features",
            "to": "/ui-kit/android/v5/call-features"
          },
          {
            "from": "/ui-kit/android/5.0/theme-introduction",
            "to": "/ui-kit/android/v5/theme-introduction"
          },
          {
            "from": "/ui-kit/android/5.0/color-resources",
            "to": "/ui-kit/android/v5/color-resources"
          },
          {
            "from": "/ui-kit/android/5.0/component-styling",
            "to": "/ui-kit/android/v5/component-styling"
          },
          {
            "from": "/ui-kit/android/5.0/message-bubble-styling",
            "to": "/ui-kit/android/v5/message-bubble-styling"
          },
          {
            "from": "/ui-kit/android/5.0/localize",
            "to": "/ui-kit/android/v5/localize"
          },
          {
            "from": "/ui-kit/android/5.0/sound-manager",
            "to": "/ui-kit/android/v5/sound-manager"
          },
          {
            "from": "/ui-kit/android/5.0/components-overview",
            "to": "/ui-kit/android/v5/components-overview"
          },
          {
            "from": "/ui-kit/android/5.0/conversations",
            "to": "/ui-kit/android/v5/conversations"
          },
          {
            "from": "/ui-kit/android/5.0/users",
            "to": "/ui-kit/android/v5/users"
          },
          {
            "from": "/ui-kit/android/5.0/groups",
            "to": "/ui-kit/android/v5/groups"
          },
          {
            "from": "/ui-kit/android/5.0/group-members",
            "to": "/ui-kit/android/v5/group-members"
          },
          {
            "from": "/ui-kit/android/5.0/message-header",
            "to": "/ui-kit/android/v5/message-header"
          },
          {
            "from": "/ui-kit/android/5.0/message-list",
            "to": "/ui-kit/android/v5/message-list"
          },
          {
            "from": "/ui-kit/android/5.0/message-composer",
            "to": "/ui-kit/android/v5/message-composer"
          },
          {
            "from": "/ui-kit/android/5.0/threaded-messages-header",
            "to": "/ui-kit/android/v5/threaded-messages-header"
          },
          {
            "from": "/ui-kit/android/5.0/incoming-call",
            "to": "/ui-kit/android/v5/incoming-call"
          },
          {
            "from": "/ui-kit/android/5.0/outgoing-call",
            "to": "/ui-kit/android/v5/outgoing-call"
          },
          {
            "from": "/ui-kit/android/5.0/call-buttons",
            "to": "/ui-kit/android/v5/call-buttons"
          },
          {
            "from": "/ui-kit/android/5.0/call-logs",
            "to": "/ui-kit/android/v5/call-logs"
          },
          {
            "from": "/ui-kit/android/5.0/events",
            "to": "/ui-kit/android/v5/events"
          },
          {
            "from": "/ui-kit/android/5.0/methods",
            "to": "/ui-kit/android/v5/methods"
          },
          {
            "from": "/ui-kit/android/5.0/message-template",
            "to": "/ui-kit/android/v5/message-template"
          },
          {
            "from": "/ui-kit/android/5.0/mentions-formatter-guide",
            "to": "/ui-kit/android/v5/mentions-formatter-guide"
          },
          {
            "from": "/ui-kit/android/5.0/shortcut-formatter-guide",
            "to": "/ui-kit/android/v5/shortcut-formatter-guide"
          },
          {
            "from": "/ui-kit/android/overview",
            "to": "/ui-kit/android/v4/overview"
          },
          {
            "from": "/ui-kit/android/4.0/overview",
            "to": "/ui-kit/android/v4/overview"
          },
          {
            "from": "/ui-kit/android/getting-started",
            "to": "/ui-kit/android/v4/getting-started"
          },
          {
            "from": "/ui-kit/android/4.0/getting-started",
            "to": "/ui-kit/android/v4/getting-started"
          },
          {
            "from": "/ui-kit/android/core-features",
            "to": "/ui-kit/android/v4/core-features"
          },
          {
            "from": "/ui-kit/android/4.0/core-features",
            "to": "/ui-kit/android/v4/core-features"
          },
          {
            "from": "/ui-kit/android/extensions",
            "to": "/ui-kit/android/v4/extensions"
          },
          {
            "from": "/ui-kit/android/4.0/extensions",
            "to": "/ui-kit/android/v4/extensions"
          },
          {
            "from": "/ui-kit/android/call-features",
            "to": "/ui-kit/android/v4/call-features"
          },
          {
            "from": "/ui-kit/android/4.0/call-features",
            "to": "/ui-kit/android/v4/call-features"
          },
          {
            "from": "/ui-kit/android/ai-features",
            "to": "/ui-kit/android/v4/ai-features"
          },
          {
            "from": "/ui-kit/android/4.0/ai-features",
            "to": "/ui-kit/android/v4/ai-features"
          },
          {
            "from": "/ui-kit/android/theme",
            "to": "/ui-kit/android/v4/theme"
          },
          {
            "from": "/ui-kit/android/4.0/theme",
            "to": "/ui-kit/android/v4/theme"
          },
          {
            "from": "/ui-kit/android/localize",
            "to": "/ui-kit/android/v4/localize"
          },
          {
            "from": "/ui-kit/android/4.0/localize",
            "to": "/ui-kit/android/v4/localize"
          },
          {
            "from": "/ui-kit/android/sound-manager",
            "to": "/ui-kit/android/v4/sound-manager"
          },
          {
            "from": "/ui-kit/android/4.0/sound-manager",
            "to": "/ui-kit/android/v4/sound-manager"
          },
          {
            "from": "/ui-kit/android/components-overview",
            "to": "/ui-kit/android/v4/components-overview"
          },
          {
            "from": "/ui-kit/android/4.0/components-overview",
            "to": "/ui-kit/android/v4/components-overview"
          },
          {
            "from": "/ui-kit/android/conversations",
            "to": "/ui-kit/android/v4/conversations"
          },
          {
            "from": "/ui-kit/android/4.0/conversations",
            "to": "/ui-kit/android/v4/conversations"
          },
          {
            "from": "/ui-kit/android/conversations-with-messages",
            "to": "/ui-kit/android/v4/conversations-with-messages"
          },
          {
            "from": "/ui-kit/android/4.0/conversations-with-messages",
            "to": "/ui-kit/android/v4/conversations-with-messages"
          },
          {
            "from": "/ui-kit/android/contacts",
            "to": "/ui-kit/android/v4/contacts"
          },
          {
            "from": "/ui-kit/android/4.0/contacts",
            "to": "/ui-kit/android/v4/contacts"
          },
          {
            "from": "/ui-kit/android/users",
            "to": "/ui-kit/android/v4/users"
          },
          {
            "from": "/ui-kit/android/4.0/users",
            "to": "/ui-kit/android/v4/users"
          },
          {
            "from": "/ui-kit/android/users-with-messages",
            "to": "/ui-kit/android/v4/users-with-messages"
          },
          {
            "from": "/ui-kit/android/4.0/users-with-messages",
            "to": "/ui-kit/android/v4/users-with-messages"
          },
          {
            "from": "/ui-kit/android/groups",
            "to": "/ui-kit/android/v4/groups"
          },
          {
            "from": "/ui-kit/android/4.0/groups",
            "to": "/ui-kit/android/v4/groups"
          },
          {
            "from": "/ui-kit/android/groups-with-messages",
            "to": "/ui-kit/android/v4/groups-with-messages"
          },
          {
            "from": "/ui-kit/android/4.0/groups-with-messages",
            "to": "/ui-kit/android/v4/groups-with-messages"
          },
          {
            "from": "/ui-kit/android/create-group",
            "to": "/ui-kit/android/v4/create-group"
          },
          {
            "from": "/ui-kit/android/4.0/create-group",
            "to": "/ui-kit/android/v4/create-group"
          },
          {
            "from": "/ui-kit/android/join-protected-group",
            "to": "/ui-kit/android/v4/join-protected-group"
          },
          {
            "from": "/ui-kit/android/4.0/join-protected-group",
            "to": "/ui-kit/android/v4/join-protected-group"
          },
          {
            "from": "/ui-kit/android/group-members",
            "to": "/ui-kit/android/v4/group-members"
          },
          {
            "from": "/ui-kit/android/4.0/group-members",
            "to": "/ui-kit/android/v4/group-members"
          },
          {
            "from": "/ui-kit/android/group-add-members",
            "to": "/ui-kit/android/v4/group-add-members"
          },
          {
            "from": "/ui-kit/android/4.0/group-add-members",
            "to": "/ui-kit/android/v4/group-add-members"
          },
          {
            "from": "/ui-kit/android/banned-members",
            "to": "/ui-kit/android/v4/banned-members"
          },
          {
            "from": "/ui-kit/android/4.0/banned-members",
            "to": "/ui-kit/android/v4/banned-members"
          },
          {
            "from": "/ui-kit/android/transfer-ownership",
            "to": "/ui-kit/android/v4/transfer-ownership"
          },
          {
            "from": "/ui-kit/android/4.0/transfer-ownership",
            "to": "/ui-kit/android/v4/transfer-ownership"
          },
          {
            "from": "/ui-kit/android/group-details",
            "to": "/ui-kit/android/v4/group-details"
          },
          {
            "from": "/ui-kit/android/4.0/group-details",
            "to": "/ui-kit/android/v4/group-details"
          },
          {
            "from": "/ui-kit/android/messages",
            "to": "/ui-kit/android/v4/messages"
          },
          {
            "from": "/ui-kit/android/4.0/messages",
            "to": "/ui-kit/android/v4/messages"
          },
          {
            "from": "/ui-kit/android/message-header",
            "to": "/ui-kit/android/v4/message-header"
          },
          {
            "from": "/ui-kit/android/4.0/message-header",
            "to": "/ui-kit/android/v4/message-header"
          },
          {
            "from": "/ui-kit/android/message-list",
            "to": "/ui-kit/android/v4/message-list"
          },
          {
            "from": "/ui-kit/android/4.0/message-list",
            "to": "/ui-kit/android/v4/message-list"
          },
          {
            "from": "/ui-kit/android/message-template",
            "to": "/ui-kit/android/v4/message-template"
          },
          {
            "from": "/ui-kit/android/4.0/message-template",
            "to": "/ui-kit/android/v4/message-template"
          },
          {
            "from": "/ui-kit/android/message-composer",
            "to": "/ui-kit/android/v4/message-composer"
          },
          {
            "from": "/ui-kit/android/4.0/message-composer",
            "to": "/ui-kit/android/v4/message-composer"
          },
          {
            "from": "/ui-kit/android/message-information",
            "to": "/ui-kit/android/v4/message-information"
          },
          {
            "from": "/ui-kit/android/4.0/message-information",
            "to": "/ui-kit/android/v4/message-information"
          },
          {
            "from": "/ui-kit/android/threaded-messages",
            "to": "/ui-kit/android/v4/threaded-messages"
          },
          {
            "from": "/ui-kit/android/4.0/threaded-messages",
            "to": "/ui-kit/android/v4/threaded-messages"
          },
          {
            "from": "/ui-kit/android/interactive-form-bubble",
            "to": "/ui-kit/android/v4/interactive-form-bubble"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-form-bubble",
            "to": "/ui-kit/android/v4/interactive-form-bubble"
          },
          {
            "from": "/ui-kit/android/interactive-form-message",
            "to": "/ui-kit/android/v4/interactive-form-message"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-form-message",
            "to": "/ui-kit/android/v4/interactive-form-message"
          },
          {
            "from": "/ui-kit/android/interactive-card-bubble",
            "to": "/ui-kit/android/v4/interactive-card-bubble"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-card-bubble",
            "to": "/ui-kit/android/v4/interactive-card-bubble"
          },
          {
            "from": "/ui-kit/android/interactive-card-message",
            "to": "/ui-kit/android/v4/interactive-card-message"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-card-message",
            "to": "/ui-kit/android/v4/interactive-card-message"
          },
          {
            "from": "/ui-kit/android/interactive-element-entity",
            "to": "/ui-kit/android/v4/interactive-element-entity"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-element-entity",
            "to": "/ui-kit/android/v4/interactive-element-entity"
          },
          {
            "from": "/ui-kit/android/interactive-action-entity",
            "to": "/ui-kit/android/v4/interactive-action-entity"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-action-entity",
            "to": "/ui-kit/android/v4/interactive-action-entity"
          },
          {
            "from": "/ui-kit/android/interactive-custom-message",
            "to": "/ui-kit/android/v4/interactive-custom-message"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-custom-message",
            "to": "/ui-kit/android/v4/interactive-custom-message"
          },
          {
            "from": "/ui-kit/android/interactive-button-element",
            "to": "/ui-kit/android/v4/interactive-button-element"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-button-element",
            "to": "/ui-kit/android/v4/interactive-button-element"
          },
          {
            "from": "/ui-kit/android/interactive-textinput-element",
            "to": "/ui-kit/android/v4/interactive-textinput-element"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-textinput-element",
            "to": "/ui-kit/android/v4/interactive-textinput-element"
          },
          {
            "from": "/ui-kit/android/interactive-label-element",
            "to": "/ui-kit/android/v4/interactive-label-element"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-label-element",
            "to": "/ui-kit/android/v4/interactive-label-element"
          },
          {
            "from": "/ui-kit/android/interactive-single-select-element",
            "to": "/ui-kit/android/v4/interactive-single-select-element"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-single-select-element",
            "to": "/ui-kit/android/v4/interactive-single-select-element"
          },
          {
            "from": "/ui-kit/android/interactive-radio-button-element",
            "to": "/ui-kit/android/v4/interactive-radio-button-element"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-radio-button-element",
            "to": "/ui-kit/android/v4/interactive-radio-button-element"
          },
          {
            "from": "/ui-kit/android/interactive-checkbox-element",
            "to": "/ui-kit/android/v4/interactive-checkbox-element"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-checkbox-element",
            "to": "/ui-kit/android/v4/interactive-checkbox-element"
          },
          {
            "from": "/ui-kit/android/interactive-spinner-element",
            "to": "/ui-kit/android/v4/interactive-spinner-element"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-spinner-element",
            "to": "/ui-kit/android/v4/interactive-spinner-element"
          },
          {
            "from": "/ui-kit/android/interactive-scheduler-message",
            "to": "/ui-kit/android/v4/interactive-scheduler-message"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-scheduler-message",
            "to": "/ui-kit/android/v4/interactive-scheduler-message"
          },
          {
            "from": "/ui-kit/android/interactive-date-time-element",
            "to": "/ui-kit/android/v4/interactive-date-time-element"
          },
          {
            "from": "/ui-kit/android/4.0/interactive-date-time-element",
            "to": "/ui-kit/android/v4/interactive-date-time-element"
          },
          {
            "from": "/ui-kit/android/call-overview",
            "to": "/ui-kit/android/v4/call-overview"
          },
          {
            "from": "/ui-kit/android/4.0/call-overview",
            "to": "/ui-kit/android/v4/call-overview"
          },
          {
            "from": "/ui-kit/android/incoming-call",
            "to": "/ui-kit/android/v4/incoming-call"
          },
          {
            "from": "/ui-kit/android/4.0/incoming-call",
            "to": "/ui-kit/android/v4/incoming-call"
          },
          {
            "from": "/ui-kit/android/ongoing-call",
            "to": "/ui-kit/android/v4/ongoing-call"
          },
          {
            "from": "/ui-kit/android/4.0/ongoing-call",
            "to": "/ui-kit/android/v4/ongoing-call"
          },
          {
            "from": "/ui-kit/android/outgoing-call",
            "to": "/ui-kit/android/v4/outgoing-call"
          },
          {
            "from": "/ui-kit/android/4.0/outgoing-call",
            "to": "/ui-kit/android/v4/outgoing-call"
          },
          {
            "from": "/ui-kit/android/call-buttons",
            "to": "/ui-kit/android/v4/call-buttons"
          },
          {
            "from": "/ui-kit/android/4.0/call-buttons",
            "to": "/ui-kit/android/v4/call-buttons"
          },
          {
            "from": "/ui-kit/android/call-logs",
            "to": "/ui-kit/android/v4/call-logs"
          },
          {
            "from": "/ui-kit/android/4.0/call-logs",
            "to": "/ui-kit/android/v4/call-logs"
          },
          {
            "from": "/ui-kit/android/call-log-details",
            "to": "/ui-kit/android/v4/call-log-details"
          },
          {
            "from": "/ui-kit/android/4.0/call-log-details",
            "to": "/ui-kit/android/v4/call-log-details"
          },
          {
            "from": "/ui-kit/android/call-log-history",
            "to": "/ui-kit/android/v4/call-log-history"
          },
          {
            "from": "/ui-kit/android/4.0/call-log-history",
            "to": "/ui-kit/android/v4/call-log-history"
          },
          {
            "from": "/ui-kit/android/call-log-recording",
            "to": "/ui-kit/android/v4/call-log-recording"
          },
          {
            "from": "/ui-kit/android/4.0/call-log-recording",
            "to": "/ui-kit/android/v4/call-log-recording"
          },
          {
            "from": "/ui-kit/android/call-log-participants",
            "to": "/ui-kit/android/v4/call-log-participants"
          },
          {
            "from": "/ui-kit/android/4.0/call-log-participants",
            "to": "/ui-kit/android/v4/call-log-participants"
          },
          {
            "from": "/ui-kit/android/call-log-with-details",
            "to": "/ui-kit/android/v4/call-log-with-details"
          },
          {
            "from": "/ui-kit/android/4.0/call-log-with-details",
            "to": "/ui-kit/android/v4/call-log-with-details"
          },
          {
            "from": "/ui-kit/android/avatar",
            "to": "/ui-kit/android/v4/avatar"
          },
          {
            "from": "/ui-kit/android/4.0/avatar",
            "to": "/ui-kit/android/v4/avatar"
          },
          {
            "from": "/ui-kit/android/status-indicator",
            "to": "/ui-kit/android/v4/status-indicator"
          },
          {
            "from": "/ui-kit/android/4.0/status-indicator",
            "to": "/ui-kit/android/v4/status-indicator"
          },
          {
            "from": "/ui-kit/android/badge",
            "to": "/ui-kit/android/v4/badge"
          },
          {
            "from": "/ui-kit/android/4.0/badge",
            "to": "/ui-kit/android/v4/badge"
          },
          {
            "from": "/ui-kit/android/receipt",
            "to": "/ui-kit/android/v4/receipt"
          },
          {
            "from": "/ui-kit/android/4.0/receipt",
            "to": "/ui-kit/android/v4/receipt"
          },
          {
            "from": "/ui-kit/android/date",
            "to": "/ui-kit/android/v4/date"
          },
          {
            "from": "/ui-kit/android/4.0/date",
            "to": "/ui-kit/android/v4/date"
          },
          {
            "from": "/ui-kit/android/text-bubble",
            "to": "/ui-kit/android/v4/text-bubble"
          },
          {
            "from": "/ui-kit/android/4.0/text-bubble",
            "to": "/ui-kit/android/v4/text-bubble"
          },
          {
            "from": "/ui-kit/android/image-bubble",
            "to": "/ui-kit/android/v4/image-bubble"
          },
          {
            "from": "/ui-kit/android/4.0/image-bubble",
            "to": "/ui-kit/android/v4/image-bubble"
          },
          {
            "from": "/ui-kit/android/file-bubble",
            "to": "/ui-kit/android/v4/file-bubble"
          },
          {
            "from": "/ui-kit/android/4.0/file-bubble",
            "to": "/ui-kit/android/v4/file-bubble"
          },
          {
            "from": "/ui-kit/android/audio-bubble",
            "to": "/ui-kit/android/v4/audio-bubble"
          },
          {
            "from": "/ui-kit/android/4.0/audio-bubble",
            "to": "/ui-kit/android/v4/audio-bubble"
          },
          {
            "from": "/ui-kit/android/video-bubble",
            "to": "/ui-kit/android/v4/video-bubble"
          },
          {
            "from": "/ui-kit/android/4.0/video-bubble",
            "to": "/ui-kit/android/v4/video-bubble"
          },
          {
            "from": "/ui-kit/android/message-bubble",
            "to": "/ui-kit/android/v4/message-bubble"
          },
          {
            "from": "/ui-kit/android/4.0/message-bubble",
            "to": "/ui-kit/android/v4/message-bubble"
          },
          {
            "from": "/ui-kit/android/message-input",
            "to": "/ui-kit/android/v4/message-input"
          },
          {
            "from": "/ui-kit/android/4.0/message-input",
            "to": "/ui-kit/android/v4/message-input"
          },
          {
            "from": "/ui-kit/android/action-sheet",
            "to": "/ui-kit/android/v4/action-sheet"
          },
          {
            "from": "/ui-kit/android/4.0/action-sheet",
            "to": "/ui-kit/android/v4/action-sheet"
          },
          {
            "from": "/ui-kit/android/media-recorder",
            "to": "/ui-kit/android/v4/media-recorder"
          },
          {
            "from": "/ui-kit/android/4.0/media-recorder",
            "to": "/ui-kit/android/v4/media-recorder"
          },
          {
            "from": "/ui-kit/android/list-item",
            "to": "/ui-kit/android/v4/list-item"
          },
          {
            "from": "/ui-kit/android/4.0/list-item",
            "to": "/ui-kit/android/v4/list-item"
          },
          {
            "from": "/ui-kit/android/list-base",
            "to": "/ui-kit/android/v4/list-base"
          },
          {
            "from": "/ui-kit/android/4.0/list-base",
            "to": "/ui-kit/android/v4/list-base"
          },
          {
            "from": "/ui-kit/android/events",
            "to": "/ui-kit/android/v4/events"
          },
          {
            "from": "/ui-kit/android/4.0/events",
            "to": "/ui-kit/android/v4/events"
          },
          {
            "from": "/ui-kit/android/methods",
            "to": "/ui-kit/android/v4/methods"
          },
          {
            "from": "/ui-kit/android/4.0/methods",
            "to": "/ui-kit/android/v4/methods"
          },
          {
            "from": "/ui-kit/android/multi-tab-chat-ui-guide",
            "to": "/ui-kit/android/v4/multi-tab-chat-ui-guide"
          },
          {
            "from": "/ui-kit/android/4.0/multi-tab-chat-ui-guide",
            "to": "/ui-kit/android/v4/multi-tab-chat-ui-guide"
          },
          {
            "from": "/ui-kit/android/mentions-formatter-guide",
            "to": "/ui-kit/android/v4/mentions-formatter-guide"
          },
          {
            "from": "/ui-kit/android/4.0/mentions-formatter-guide",
            "to": "/ui-kit/android/v4/mentions-formatter-guide"
          },
          {
            "from": "/ui-kit/android/shortcut-formatter-guide",
            "to": "/ui-kit/android/v4/shortcut-formatter-guide"
          },
          {
            "from": "/ui-kit/android/4.0/shortcut-formatter-guide",
            "to": "/ui-kit/android/v4/shortcut-formatter-guide"
          },
          {
            "from": "/ui-kit/android/3.0/conversationlist",
            "to": "/ui-kit/android/v3/conversationlist"
          },
          {
            "from": "/ui-kit/android/3.0/key-concepts",
            "to": "/ui-kit/android/v3/key-concepts"
          },
          {
            "from": "/ui-kit/android/3.0/how-to-add-uikit-module",
            "to": "/ui-kit/android/v3/how-to-add-uikit-module"
          },
          {
            "from": "/ui-kit/android/3.0/overview",
            "to": "/ui-kit/android/v3/overview"
          },
          {
            "from": "/ui-kit/android/3.0/android-java-ui-components",
            "to": "/ui-kit/android/v3/android-java-ui-components"
          },
          {
            "from": "/ui-kit/android/3.0/android-customize-ui-kit",
            "to": "/ui-kit/android/v3/android-customize-ui-kit"
          },
          {
            "from": "/ui-kit/android/3.0/folder-structure-android-uikit",
            "to": "/ui-kit/android/v3/folder-structure-android-uikit"
          },
          {
            "from": "/ui-kit/android/2.0/key-concepts",
            "to": "/ui-kit/android/v2/key-concepts"
          },
          {
            "from": "/ui-kit/android/2.0/message-structure-and-hierarchy",
            "to": "/ui-kit/android/v2/message-structure-and-hierarchy"
          },
          {
            "from": "/ui-kit/android/2.0/overview",
            "to": "/ui-kit/android/v2/overview"
          },
          {
            "from": "/ui-kit/android/2.0/ui-components",
            "to": "/ui-kit/android/v2/ui-components"
          },
          {
            "from": "/ui-kit/android/2.0/customize-ui-kit",
            "to": "/ui-kit/android/v2/customize-ui-kit"
          },
          {
            "from": "/ui-kit/android/2.0/folder-structure-android-uikit",
            "to": "/ui-kit/android/v2/folder-structure-android-uikit"
          },
          {
            "from": "/ai/overview",
            "to": "/fundamentals/ai-user-copilot/overview"
          },
          {
            "from": "/ai/conversation-starter",
            "to": "/fundamentals/ai-user-copilot/conversation-starter"
          },
          {
            "from": "/ai/smart-replies",
            "to": "/fundamentals/ai-user-copilot/smart-replies"
          },
          {
            "from": "/ai/conversation-summary",
            "to": "/fundamentals/ai-user-copilot/conversation-summary"
          },
          {
            "from": "/webhooks/overview",
            "to": "/fundamentals/webhooks-overview"
          },
          {
            "from": "/webhooks/webhooks-management",
            "to": "/fundamentals/webhooks-management"
          },
          {
            "from": "/webhooks/webhooks-events",
            "to": "/fundamentals/webhooks-events"
          },
          {
            "from": "/webhooks/webhooks-legacy-overview",
            "to": "/fundamentals/webhooks-legacy-overview"
          },
          {
            "from": "/webhooks/webhooks-legacy-management",
            "to": "/fundamentals/webhooks-legacy-management"
          },
          {
            "from": "/webhooks/webhooks-legacy-events",
            "to": "/fundamentals/webhooks-legacy-events"
          },
          {
            "from": "/ai/bots",
            "to": "/ai-chatbots/bots"
          },
          {
            "from": "/ai/personalities",
            "to": "/ai-chatbots/instructions"
          },
          {
            "from": "/bots/overview",
            "to": "/ai-chatbots/non-ai-bots"
          },
          {
            "from": "/extensions/notification-extensions",
            "to": "/fundamentals/notification-extensions"
          },
          {
            "from": "/extensions/message-shortcuts",
            "to": "/fundamentals/message-shortcuts"
          },
          {
            "from": "/extensions/avatars",
            "to": "/fundamentals/avatars"
          },
          {
            "from": "/extensions/thumbnail-generation",
            "to": "/fundamentals/thumbnail-generation"
          },
          {
            "from": "/extensions/link-preview",
            "to": "/fundamentals/link-preview"
          },
          {
            "from": "/extensions/rich-media-preview",
            "to": "/fundamentals/rich-media-preview"
          },
          {
            "from": "/extensions/voice-transcription",
            "to": "/fundamentals/voice-transcription"
          },
          {
            "from": "/extensions/pin-message",
            "to": "/fundamentals/pin-message"
          },
          {
            "from": "/extensions/save-message",
            "to": "/fundamentals/save-message"
          },
          {
            "from": "/extensions/tinyurl",
            "to": "/fundamentals/tinyurl"
          },
          {
            "from": "/extensions/bitly",
            "to": "/fundamentals/bitly"
          },
          {
            "from": "/extensions/email-replies",
            "to": "/fundamentals/email-replies"
          },
          {
            "from": "/extensions/mentions",
            "to": "/fundamentals/mentions"
          },
          {
            "from": "/extensions/giphy",
            "to": "/fundamentals/giphy"
          },
          {
            "from": "/extensions/tenor",
            "to": "/fundamentals/tenor"
          },
          {
            "from": "/extensions/gfycat",
            "to": "/fundamentals/gfycat"
          },
          {
            "from": "/extensions/reminders",
            "to": "/fundamentals/reminders"
          },
          {
            "from": "/extensions/smart-replies",
            "to": "/fundamentals/smart-replies"
          },
          {
            "from": "/extensions/message-translation",
            "to": "/fundamentals/message-translation"
          },
          {
            "from": "/extensions/emojis",
            "to": "/fundamentals/emojis"
          },
          {
            "from": "/extensions/polls",
            "to": "/fundamentals/polls"
          },
          {
            "from": "/extensions/reactions",
            "to": "/fundamentals/reactions"
          },
          {
            "from": "/extensions/stickers-stipop",
            "to": "/fundamentals/stickers-stipop"
          },
          {
            "from": "/extensions/stickers",
            "to": "/fundamentals/stickers"
          },
          {
            "from": "/extensions/video-broadcasting",
            "to": "/fundamentals/video-broadcasting"
          },
          {
            "from": "/extensions/collaborative-whiteboard",
            "to": "/fundamentals/collaborative-whiteboard"
          },
          {
            "from": "/extensions/collaborative-document",
            "to": "/fundamentals/collaborative-document"
          },
          {
            "from": "/extensions/chatwoot",
            "to": "/fundamentals/chatwoot"
          },
          {
            "from": "/extensions/intercom",
            "to": "/fundamentals/intercom"
          },
          {
            "from": "/extensions/moderation-extensions",
            "to": "/fundamentals/moderation-extensions"
          },
          {
            "from": "/extensions/disappearing-messages",
            "to": "/fundamentals/disappearing-messages"
          },
          {
            "from": "/extensions/end-to-end-encryption",
            "to": "/fundamentals/end-to-end-encryption"
          },
          {
            "from": "/extensions/overview",
            "to": "/fundamentals/extensions-overview"
          },
          {
            "from": "/extensions/web-push-notifications",
            "to": "/notifications/web-push-notifications"
          },
          {
            "from": "/extensions/android-push-notifications",
            "to": "/notifications/android-push-notifications"
          },
          {
            "from": "/extensions/android-connection-service",
            "to": "/notifications/android-connection-service"
          },
          {
            "from": "/extensions/ios-fcm-push-notifications",
            "to": "/notifications/ios-fcm-push-notifications"
          },
          {
            "from": "/extensions/ios-apns-push-notifications",
            "to": "/notifications/ios-apns-push-notifications"
          },
          {
            "from": "/extensions/flutter-push-notifications",
            "to": "/notifications/flutter-push-notifications"
          },
          {
            "from": "/extensions/react-native-push-notifications",
            "to": "/notifications/react-native-push-notifications"
          },
          {
            "from": "/extensions/capacitor-cordova-ionic-push-notifications",
            "to": "/notifications/capacitor-cordova-ionic-push-notifications"
          },
          {
            "from": "/extensions/migration-guide-push-notifications",
            "to": "/notifications/migration-guide-push-notifications"
          },
          {
            "from": "/extensions/mute-functionality",
            "to": "/notifications/mute-functionality"
          },
          {
            "from": "/extensions/token-management",
            "to": "/notifications/token-management"
          },
          {
            "from": "/extensions/legacy-push-notifications",
            "to": "/notifications/legacy-push-notifications"
          },
          {
            "from": "/extensions/push-notifications-overview",
            "to": "/notifications/push-notification-extension-overview"
          },
          {
            "from": "/extensions/email-notifications",
            "to": "/notifications/email-notification-extension"
          },
          {
            "from": "/extensions/sms-notifications",
            "to": "/notifications/sms-notification-extension"
          },
          {
            "from": "/extensions/slow-mode",
            "to": "/moderation/slow-mode"
          },
          {
            "from": "/extensions/xss-filter",
            "to": "/moderation/xss-filter"
          },
          {
            "from": "/extensions/report-user",
            "to": "/moderation/report-user"
          },
          {
            "from": "/extensions/report-message",
            "to": "/moderation/report-message"
          },
          {
            "from": "/extensions/data-masking-filter",
            "to": "/moderation/data-masking-filter"
          },
          {
            "from": "/extensions/profanity-filter",
            "to": "/moderation/profanity-filter"
          },
          {
            "from": "/extensions/image-moderation",
            "to": "/moderation/image-moderation"
          },
          {
            "from": "/extensions/sentiment-analysis",
            "to": "/moderation/sentiment-analysis"
          },
          {
            "from": "/extensions/in-flight-message-moderation",
            "to": "/moderation/in-flight-message-moderation"
          },
          {
            "from": "/extensions/virus-malware-scanner",
            "to": "/moderation/virus-malware-scanner"
          }
        ]
      }
    ]
  ],
  "trailingSlash": false,
  "themes": [
    "@docusaurus/theme-live-codeblock"
  ],
  "clientModules": [
    "/home/jawangana/docs/src/client/define-ui-kit.js"
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "id": "docs-home",
          "path": "docs/home",
          "routeBasePath": "/home",
          "breadcrumbs": true,
          "showLastUpdateTime": true,
          "remarkPlugins": [
            [
              null,
              {
                "sync": true
              }
            ]
          ],
          "sidebarPath": "/home/jawangana/docs/sidebar_auto.js"
        },
        "blog": false,
        "theme": {
          "customCss": [
            "/home/jawangana/docs/src/css/custom.css",
            "/home/jawangana/docs/src/css/api-reference.css"
          ]
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        },
        "googleTagManager": {
          "containerId": "undefined"
        }
      }
    ]
  ],
  "stylesheets": [
    "https://fonts.googleapis.com/icon?family=Material+Icons"
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "logo": {
        "href": "/",
        "src": "/imgs/logo.svg",
        "srcDark": "/imgs/logo.svg",
        "alt": "Logo",
        "width": "150px"
      },
      "items": [
        {
          "label": "Platform",
          "type": "dropdown",
          "items": [
            {
              "type": "html",
              "value": "<div></div>",
              "className": "my-website-dropdown"
            }
          ],
          "position": "left"
        },
        {
          "label": "Integrate",
          "type": "dropdown",
          "items": [
            {
              "type": "html",
              "value": "<div></div>",
              "className": "my-website-dropdown"
            }
          ],
          "position": "left"
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "label": "Dashboard",
          "to": "https://app.cometchat.com/",
          "position": "right",
          "className": "navbar-book-demo"
        },
        {
          "label": "Contact Support",
          "to": "https://help.cometchat.com/hc/en-us/requests/new",
          "position": "right",
          "className": "schedule_a_demo_button"
        }
      ],
      "hideOnScroll": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "dart",
        "ruby",
        "groovy",
        "kotlin",
        "java",
        "swift",
        "objectivec"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "highlight-next-line-error"
        }
      ]
    },
    "algolia": {
      "appId": "6RW3CISVKU",
      "apiKey": "ca85d17c2b7e887b2f084d22e25807cf",
      "indexName": "your_index_name",
      "contextualSearch": false,
      "searchParameters": {
        "facetFilters": []
      },
      "searchPagePath": "search"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    }
  },
  "webpack": {},
  "onBrokenAnchors": "warn",
  "onBrokenMarkdownLinks": "warn",
  "markdown": {
    "format": "mdx",
    "mdx1Compat": {
      "comments": false,
      "admonitions": false,
      "headingIds": true
    },
    "mermaid": false,
    "anchors": {
      "maintainCase": false
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false
};
